image: docker:stable

services:
  - docker:dind

before_script:
  - apk --no-cache add curl

build-docker:
    tags:
        - docker
    stage: test
    script: 
        - docker build -t $CI_REGISTRY_IMAGE/relay -f docker/Dockerfile .
        - docker build -t $CI_REGISTRY_IMAGE/homechain -f docker/homechain/Dockerfile docker/homechain
        - docker build -t $CI_REGISTRY_IMAGE/sidechain -f docker/sidechain/Dockerfile docker/sidechain
        
kick-e2e:
    only: 
        - master
    tags:
        - docker
    stage: deploy
    script:
       - curl --request POST --form "token=$CI_JOB_TOKEN" --form ref=master https://gitlab.polyswarm.io/api/v4/projects/${CI_CUSTOM_PROJECT_ID_META}/trigger/pipeline
