stages:
  - lint
  - test
  - coverage
  - e2e
  - deploy
  - deployECR
  
services:
  - docker:dind

lint:
  stage: lint
  image: rust:1.31.1
  allow_failure: true
  script:
    - rustup component add rustfmt
    - cargo fmt --all -- --check
    - rustup component add clippy
    - cargo clippy

test:
  stage: test
  image: rust:1.31.1
  script:
    - cargo test --verbose

coverage:
  stage: coverage
  image: rust:1.31.1
  allow_failure: true
  coverage: '/COVERAGE:\d+\.\d+/'
  script:
    - apt-get update
    - apt-get install -y jq zsh binutils-dev libcurl4-openssl-dev zlib1g-dev libdw-dev libiberty-dev unzip cmake build-essential
    - rustup update nightly # required for kcov instrumentation
    - rustup default nightly
    - cargo install cargo-cov
    - ./testutils/collect_coverage.sh --auto

kick-e2e:
    image: $CI_CUSTOM_DEV_REGISTRY_URI/ci-images/stage:latest
    tags:
        - docker
    stage: e2e
    script:
      - set -e

      # kick e2e
      - >-
        E2E_PIPELINE_ID=`curl
        --silent
        --request POST
        --form "token=$CI_JOB_TOKEN"
        --form "variables[SOURCE_PROJECT]=$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME"
        --form "variables[SOURCE_BRANCH]=$CI_COMMIT_REF_NAME"
        --form "ref=master"
        "https://gitlab.polyswarm.io/api/v4/projects/${CI_CUSTOM_PROJECT_ID_E2E}/trigger/pipeline" | jq -r ".id"`

      # poll for it to finish
      - >-
        while [ -z $PIPELINE_STATUS ] || [ $PIPELINE_STATUS = "pending" ] || [ $PIPELINE_STATUS = "running" ]; do
          PIPELINE_STATUS=`curl \
            --silent \
            --header "PRIVATE-TOKEN: $CI_CUSTOM_CI_PAT" \
            "https://gitlab.polyswarm.io/api/v4/projects/${CI_CUSTOM_PROJECT_ID_E2E}/pipelines/$E2E_PIPELINE_ID" | jq -r ".status"`
          echo "waiting for e2e pipeline ...";
          sleep 5;
        done

      # check for success
      - >-
        if [ $PIPELINE_STATUS != "success" ]; then
          echo "failure further down the pipeline"
          exit 1
        fi

builddock:
  stage: deploy
  only:
    - master
    - feature/docker-build
  script:
    - docker build -t polyswarm/relay:latest -t polyswarm/relay:$CI_COMMIT_SHA --label git_commit_id=$CI_COMMIT_SHA -f docker/Dockerfile .
    - docker login -u $CI_CUSTOM_DOCKER_HUB_USERNAME -p $CI_CUSTOM_DOCKER_HUB_PASSWORD
    - docker push polyswarm/relay:latest
    - docker push polyswarm/relay:$CI_COMMIT_SHA

container_deployECR:
    tags:
    - docker
    stage: deployECR
    script:
    - pip install awscli
    - docker logout
    - $(aws ecr get-login --no-include-email --region us-east-1)
    - docker build -t "$REPO_URL/relay:latest" -t "$REPO_URL/relay:$CI_COMMIT_SHA" -f docker/Dockerfile .
    - docker push "$REPO_URL/relay:latest"
    - docker push "$REPO_URL/relay:$CI_COMMIT_SHA"
    only:
    - master