[relay]
    anchor_frequency = 100
    confirmations = 20
    consul = "http://consul:8500"
    community = "gamma"
    keydir = "./docker/keyfiles"

[relay.homechain]
    wsuri = "ws://homechain:8546"
    free = false
    interval = 30
    chain_id = 1337


[relay.sidechain]
    wsuri = "ws://sidechain:8546"
    free = true
    interval = 30
    chain_id = 1338


[logging]
    format = "raw"
