[relay]
    anchor_frequency = 100
    confirmations = 20

[relay.homechain]
    wsuri = "ws://homechain:8546"
    free = false

[relay.sidechain]
    wsuri = "ws://sidechain:8546"
    free = true

[logging]
    format = "raw"
