[relay]
    anchor_frequency = 100
    confirmations = 20
    consul = "http://consul:8500"
    community = "gamma"

[relay.homechain]
    wsuri = "ws://homechain:8546"
    free = false

[relay.sidechain]
    wsuri = "ws://sidechain:8546"
    free = true

[logging]
    format = "raw"
