version: '3'
services:
    consul:
        image: "consul"
        ports:
            - "8500:8500"
        networks:
            consul:
    contracts:
        depends_on:
            - homechain
            - sidechain
        image: "005789955001.dkr.ecr.us-east-1.amazonaws.com/contracts"
        environment:
            - geth=homechain
            - HOME_CHAIN=http://homechain:8545
            - SIDE_CHAIN=http://sidechain:8545
            - CONSUL=http://consul:8500
            - IPFS=http://ipfs:5001
            - OPTIONS=/config/config.yml
            - POLY_SIDECHAIN_NAME=gamma
        command: ["./scripts/migrate_and_create_config.sh"]
        volumes:
            - "../contracts:/config"
        networks:
            - homechain
            - sidechain
            - consul
