version: '3'
networks:
    homechain:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.20.0.0/24
    sidechain:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.20.1.0/24
    consul:
        driver: bridge
